name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker
    steps:
      - name: Add Git
        run: apk update && apk add git
      - name: Clone
        run: git clone --depth 100 $(echo "${{ gitea.event.repository.clone_url }}" | sed -e "s^//^//:${{ gitea.token }}@^") .
      - name: Build and Push
        run: |
          docker login ghcr.io -u "${{ secrets.ghcr_user }}" -p "${{ secrets.ghcr_token }}"
          docker build --pull -t "ghcr.io/rahn-it/traefik-gui" --squash .
          docker push "ghcr.io/rahn-it/traefik-gui"
