name: Build
on:
  push:
    branches:
      - master
      - renovate/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run check
      - run: npm run build
